excel:
  converter:
    props-map:
      grade:
        sheet-index: 0
        date-pattern: yyyy年MM月dd日
        name-location-map:
          name: B2
          address: B4
          age: D2
          date: D15
          gradeList:
            project: b8
            grade: c8
          totalGrade:
            project: B13
            grade: C13